// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PriceListsService.Data.Context;

#nullable disable

namespace PriceListsService.Migrations
{
    [DbContext(typeof(PriceListsContext))]
    [Migration("20230331125640_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PriceListsService.Domain.Models.Evaluation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ReferenceYearId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.Property<long>("VehicleId")
                        .HasColumnType("bigint");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceYearId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("PriceListsService.Domain.Models.ReferenceYear", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<int>("PriceReference")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ReferenceYears");
                });

            modelBuilder.Entity("PriceListsService.Domain.Models.Evaluation", b =>
                {
                    b.HasOne("PriceListsService.Domain.Models.ReferenceYear", "ReferenceYear")
                        .WithMany("Evaluationn")
                        .HasForeignKey("ReferenceYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReferenceYear");
                });

            modelBuilder.Entity("PriceListsService.Domain.Models.ReferenceYear", b =>
                {
                    b.Navigation("Evaluationn");
                });
#pragma warning restore 612, 618
        }
    }
}
