// <auto-generated />
using AuthService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20230331151015_Change default user password")]
    partial class Changedefaultuserpassword
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthService.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "contato@vpl.com.br",
                            Name = "Contato",
                            Password = "CTUsd8zLybZuAyNWBTLEa6EKM4XpZtRPH77DscmRhOYcui9+fbdf/pu3pZJA1bbKiMn1r+SxLorPh24+LxtLVKcNyTFGtsypvR27SJE6sDJrVXTMLcc8rqe7eZwvQLDwlrLRTsS6UV3C33HLv6jd5FSDc+xQPno/aHUtOQdlit2UXF82o1nKitVQ7Uzm5IcECqdZTWTj0CyZLs9xIgJZO1Jipesj+LhaTk7G3MMFjg6JIs0mmuI2BSrqtxg5BUDdY+l8zRqqu4ECsuP57G1VR1HF2U1x7MiRmo4f2q3aBd1P9NaVHF21+JehDGQCRIjOAu+SY0Q7sl42q71TWpDbndEpqVE/MMqciDefbbyDqfub4QfrykjQqib6RezwTyIGUQrRV9c/+j2xlPZ5Yu+tiBbTmk0fJuxUNjiRX90dINo="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
