// <auto-generated />
using AuthService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AuthContext))]
    partial class AuthContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthService.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "contato@vpl.com.br",
                            Name = "Contato",
                            Password = "D898LVAi78m3UDDxMwlo7rJQD7HIh9/W588CiBSTSozzddSs5PFEPb44hFEdbOyAQiNB1hk4LZe6LsO0N91nQXdFYddp7l3Uw754KniUfF+n7PjuQiEWA4PrGAmTzwCi6UCPF+IQdFvj45VGre4Yx97XnBaDdJmrW/9nNwib6zyY1Kq5H6XF7u13WSnhCidPrqCn5+fjQwWHxeWQNaPovjYLsmLnhDIsYe0wVv86L14h9zieVEfo0RTU3k0I/V+P34+Vo9Xry/dsMM9wqil+8OnNU99nqi8xKBEAPUDNJDbxy+/5+anMfFmVv4HG7+ZSmxg61/U/0nz3wl0jm+B+txDvAYH3fbs4MqEgFDebotvSlINXDaCKv9rZO9wxlxJn2jd21ahTDeRDhnogsg+3RoLs8cIdakjspVeElG6qtLQ="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
