// <auto-generated />
using AuthService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthService.Migrations
{
    [DbContext(typeof(AuthContext))]
    [Migration("20230414131241_Ajustar hash da senha")]
    partial class Ajustarhashdasenha
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AuthService.Domain.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Email = "contato@vpl.com.br",
                            Name = "Contato",
                            Password = "Wun5cxwA59NNaGw9+AwltBdKyAd5Zaqrq4bfSk12qquUbOoMLCFTKU2ApkHBhgEHhyREW8KVs8aDJRKMJDjMPychwJLSL+g6BT7CcCVCxgNn4JWoHauvM9z1M2k6dkE72gTHoUMbAKtRPGsMJnotH7KT0KZhCR8ZHzp+z7VxGpjatf5m934b1Haw3IYoetClUWkH3zH03GTHGblcoyyEKqfYO9x8acoteKQ85/l3Fymgd2UQ74RIMLrERIrY+bpiZHoC5yTThMkmyjHWpaYpnAqvSZZeNQVjAw/MS0/AcJaAwbr+0FwaPtQbS6fAVOHjzW35jQFurPUuTMF12nNUzna2T7KA7YCnPPYhWL7o7cLDRcwsXI5+X3ll9ENS1GATKCXkVimu4W7V22jUS7HRKe9HfAbLDSb2EmtD6VeWb1A="
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
